"""Change sqlalchemy.url settings

Revision ID: 4df5b71b9d07
Revises: 6652028e2dad
Create Date: 2024-03-17 11:42:40.804228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df5b71b9d07'
down_revision: Union[str, None] = '6652028e2dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
