"""Change the type of column additional_info

Revision ID: 6652028e2dad
Revises: 8a8b1a66c43d
Create Date: 2024-03-17 11:00:08.516510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "6652028e2dad"
down_revision: Union[str, None] = "8a8b1a66c43d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        text(
            "ALTER TABLE contacts ALTER COLUMN additional_info TYPE JSON USING additional_info::json"
        )
    )
    op.alter_column(
        "contacts",
        "additional_info",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "additional_info",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
