"""Change max_length of additional_info

Revision ID: 8ff81c94d561
Revises: fb396bd958a2
Create Date: 2024-03-15 18:40:42.595874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff81c94d561'
down_revision: Union[str, None] = 'fb396bd958a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'additional_info',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'additional_info',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###
